### ISSUE TITLE
examples/output/test001.isdoc.pdf is invalid PDF/A

### ISSUE THREAD

**Issue by deltazero-cz** [isdoc/isdoc.pdf#1]
Hi,
I'd like to report that **test001.isdoc.pdf** of examples here declares itself as a PDF/A-1B, which is invalid for the obvious reason of having an attachment. Pls upgrade this example to PDF/A-3B.

PS: I'm working on bash "isdoc-pdf" for Unix environment (Linux & Mac), utilising Ghostscript to attach invoice.isdoc to a pdf and convert it to PDF/A-3B. Will share later :-)

**Comment by kosek** [comment]
Thanks for report, yes examples were using wrong PDF profile. Examples and code are fixed now.
However please note that ISDOC.PDF should be PDF/A-3a not PDF/A-3b file, see https://isdoc.cz/6.0.2/doc/isdoc.html#reprezentace-isdoc.pdf
