### ISSUE TITLE
isdoc-pdf (PDF + ISDOC -> PDF/A-3B convertor) pro bash (linux, osx)

### ISSUE THREAD

**Issue by deltazero-cz** [isdoc/isdoc.pdf#2]
Dobrý večer,
rád bych se s Vámi podělil o můj čerstvě vzniklý [isdoc-pdf](https://github.com/deltazero-cz/isdoc-pdf), konvertor pro převod PDF (obyčejných) a ISDOC souborů na ISDOC.PDF, tedy PDF/A-3B obsahující ISDOC jako přílohu
- je to určené pro Unixové prostředí (Linux, OSX). Běží to v bashi a potřebuje to Ghostscript 9.27 nebo novější (`sudo apt install ghostscript`). Testováno na MacOS Mojave, Ubuntu 20.04.4 LTS a Debian Buster
- výsledky jsou PDF/A-3B compliant podle veraPDF i Adobe Acrobat Reader Pro

Dále posílám i [node-isdoc-pdf](https://github.com/deltazero-cz/node-isdoc-pdf), tj. Node.js wrapper pro výše uvedený script, který nad rámec tvorby ISDOC.PDF umí i
- extrahovat ISDOC z PDF
- přečíst a rámcově pracovat s ISDOCem
- vytvořit novou fakturu ve formátu ISDOC
- validovat ISDOC vůči XSD schématu

Budu rád, pokud to sami vyzkoušíte a třeba uvedete odkaz zde v readme.

Na závěr bych rád upozornil, že aktuální ISDOC Reader 3.0.1 neumí otevřít ISDOCy než 6.0.1, neotevře tedy ani zde uvedené příklady.

Ať se daří 🍻
DO

**Comment by kosek** [comment]
Díky, odkazy jsem přidal, byť jsem neměl příležitost vyzkoušet.

> Na závěr bych rád upozornil, že aktuální ISDOC Reader 3.0.1 neumí otevřít ISDOCy než 6.0.1, neotevře tedy ani zde uvedené příklady.

Pokud vím, ABRA zatím bohužel neplánuje aktualizaci jejich čtečky.

**Comment by deltazero-cz** [comment]
Děkuji za zveřejnění i za upozornění na jiný standard PDF/A v předchozím threadu.

I tento můj nástroj generuje, po vzoru ZUGFeRDu, PDF/A-3B, bohužel nemám ahnung, jak z něj udělat 3A. Považujete to za velký problém?

**Comment by kosek** [comment]
Pokud vím MVČR požadavek na PDF/A-3a zavedlo hlavně pro příjem faktur veřejným sektorem, kde je požadavek na to, aby PDF dokumenty byly přístupné. Prakticky to problém nebude, PDF dokument s fakturou se zobrazí, ale formálně zcela v pořádku nebude.
